# Generated by Django 4.2.7 on 2023-12-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.TextField(db_column='email', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='repass',
            field=models.TextField(db_column='password', null=True),
        ),
    ]
