# Generated by Django 4.2.7 on 2023-12-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mob',
            field=models.BigIntegerField(db_column='mob', null=True),
        ),
    ]
