# Generated by Django 5.0.1 on 2024-01-07 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantiy',
            new_name='quantity',
        ),
    ]
